M48
; DRILL file {KiCad 8.0.7} date 2025-02-08T22:14:52+0200
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-02-08T22:14:52+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1311
%
G90
G05
T1
X0.0701Y-0.135
X0.5701Y-0.135
X0.8652Y-0.1351
X1.3652Y-0.1351
M30
