M48
; DRILL file {KiCad 9.0.7} date 2026-01-29T18:33:58+0200
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-01-29T18:33:58+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0394
%
G90
G05
T1
X0.0Y0.0
X0.0Y-0.1
X0.0Y-0.2
X0.0Y-0.3
X0.0Y-0.4
X0.0Y-0.5
X0.2713Y-0.2
X0.35Y-0.2
X0.6Y0.0
X0.6Y-0.1
X0.6Y-0.2
X0.6Y-0.3
X0.6Y-0.4
X0.6Y-0.5
M30
