M48
; DRILL file {KiCad 8.0.7} date 2025-02-07T21:24:41+0200
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-02-07T21:24:41+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1311
%
G90
G05
T1
X1.03Y-0.5
X1.03Y-2.6
X1.03Y-4.1
X1.03Y-6.2
X1.2374Y-3.1145
X1.2374Y-3.6145
M30
