M48
; DRILL file {KiCad 9.0.5-9.0.5~ubuntu24.04.1} date 2025-10-24T11:05:20+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-10-24T11:05:20+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.5-9.0.5~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.330
%
G90
G05
T1
X-6.35Y1.27
X-6.35Y-52.07
X104.523Y1.27
X104.523Y-52.07
M30
