M48
; DRILL file {KiCad 9.0.2} date 2025-07-06T14:36:22+0200
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-07-06T14:36:22+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1311
%
G90
G05
T1
X-0.06Y-2.22
X0.44Y-2.22
X0.8Y-2.0
X2.9Y-2.0
X3.3Y-2.0
X5.4Y-2.0
M30
