M48
; DRILL file {KiCad 9.0.4} date 2025-09-21T20:59:15+0200
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-09-21T20:59:15+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0276
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0472
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0669
%
G90
G05
T1
X6.42Y-4.28
X6.4987Y-4.28
X6.799Y-6.9723
X6.799Y-7.051
T2
X6.695Y-4.65
X7.4745Y-4.65
T3
X5.9Y-3.1
X5.9Y-3.8
X6.0Y-3.1
X6.0Y-3.8
X6.1Y-3.1
X6.1Y-3.8
X6.2Y-3.1
X6.2Y-3.8
M30
