M48
; DRILL file {KiCad (6.0.5)} date Mon Aug 15 11:21:11 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-08-15T11:21:11+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0787
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0984
%
G90
G05
T1
X5.6772Y-3.6122
X5.8957Y-3.6122
T2
X5.6004Y-3.2776
X5.6004Y-5.6201
X7.4311Y-3.2776
X7.4311Y-5.6201
T0
M30
