M48
; DRILL file {KiCad 8.0.7} date 2025-02-09T12:46:06+0200
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-02-09T12:46:06+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1417
%
G90
G05
T1
X-0.05Y0.0
X-0.05Y-1.0236
X0.9736Y0.0
X0.9736Y-1.0236
M30
