M48
; DRILL file {KiCad 9.0.7-9.0.7~ubuntu24.04.1} date 2026-01-12T12:44:30+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-01-12T12:44:30+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7-9.0.7~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.330
%
G90
G05
T1
X-6.35Y1.27
X-6.35Y-52.07
X104.523Y1.27
X104.523Y-52.07
M30
