M48
; DRILL file {KiCad 9.0.2} date 2025-08-23T11:57:22+0200
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-08-23T11:57:22+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0394
%
G90
G05
T1
X0.0Y0.0
X0.0Y-0.1
X0.0Y-0.2
X0.2Y0.0
X0.2Y-0.1
X0.2Y-0.2
X0.7Y0.0
X0.7Y-0.1
X0.7Y-0.2
M30
