package name.bizna.emu65816;

import name.bizna.emu65816.addressingmode.*;
import name.bizna.emu65816.opcode.*;

import java.util.ArrayList;
import java.util.List;

import static name.bizna.emu65816.OpCodeName.*;

public class OpCodeTable
{
  @SuppressWarnings("DuplicatedCode")
  public static OpCode[] createTable()
  {
    List<OpCode> opCodes = new ArrayList<>();
    add(opCodes, new OpCode_BRK(BRK_Interrupt));
    add(opCodes, new OpCode_ORA(ORA_DirectPageIndexedIndirectWithX, new DirectIndexedIndirectWithXCycles(true)));
    add(opCodes, new OpCode_COP(COP_Interrupt));
    add(opCodes, new OpCode_ORA(ORA_StackRelative, new StackRelativeCycles(true)));
    add(opCodes, new OpCode_TSB_Memory(TSB_DirectPage, new DirectRMWCycles()));
    add(opCodes, new OpCode_ORA(ORA_DirectPage, new DirectCycles(true)));
    add(opCodes, new OpCode_ASL_Memory(ASL_DirectPage, new DirectRMWCycles()));
    add(opCodes, new OpCode_ORA(ORA_DirectPageIndirectLong, new DirectIndirectLongCycles(true)));
    add(opCodes, new OpCode_PHP(PHP_StackImplied, new StackImpliedPHPCycles()));
    add(opCodes, new OpCode_ORA(ORA_Immediate, new ImmediateCycles()));
    add(opCodes, new OpCode_ASL_Memory(ASL_Accumulator, new AccumulatorCycles()));
    add(opCodes, new OpCode_PHD(PHD_StackImplied, new StackImpliedPHDCycles()));
    add(opCodes, new OpCode_TSB_Memory(TSB_Absolute, new AbsoluteRMWCycles()));
    add(opCodes, new OpCode_ORA(ORA_Absolute, new AbsoluteCycles(true)));
    add(opCodes, new OpCode_ASL_Memory(ASL_Absolute, new AbsoluteRMWCycles()));
    add(opCodes, new OpCode_ORA(ORA_AbsoluteLong, new AbsoluteLongCycles(true)));
    add(opCodes, new OpCode_BPL(BPL_ProgramCounterRelative, new RelativeCycles()));
    add(opCodes, new OpCode_ORA(ORA_DirectPageIndirectIndexedWithY, new DirectIndirectIndexedWithYCycles(true)));
    add(opCodes, new OpCode_ORA(ORA_DirectPageIndirect, new DirectIndirectCycles(true)));
    add(opCodes, new OpCode_ORA(ORA_StackRelativeIndirectIndexedWithY, new StackRelativeIndirectIndexedWithYCycles(true)));
    add(opCodes, new OpCode_TRB_Memory(TRB_DirectPage, new DirectRMWCycles()));
    add(opCodes, new OpCode_ORA(ORA_DirectPageIndexedWithX, new DirectIndexedWithXCycles(true)));
    add(opCodes, new OpCode_ASL_Memory(ASL_DirectPageIndexedWithX, new DirectIndexedWithXRMWCycles()));
    add(opCodes, new OpCode_ORA(ORA_DirectPageIndirectLongIndexedWithY, new DirectIndirectLongIndexedWithYCycles(true)));
    add(opCodes, new OpCode_CLC(CLC_Implied, new ImpliedCycles()));
    add(opCodes, new OpCode_ORA(ORA_AbsoluteIndexedWithY, new AbsoluteIndexedWithYCycles(true)));
    add(opCodes, new OpCode_INC_Memory(INC_Accumulator, new AccumulatorCycles()));
    add(opCodes, new OpCode_TCS(TCS_Implied, new ImpliedCycles()));
    add(opCodes, new OpCode_TRB_Memory(TRB_Absolute, new AbsoluteRMWCycles()));
    add(opCodes, new OpCode_ORA(ORA_AbsoluteIndexedWithX, new AbsoluteIndexedWithXCycles(true)));
    add(opCodes, new OpCode_ASL_Memory(ASL_AbsoluteIndexedWithX, new AbsoluteIndexedWithXRMWCycles()));
    add(opCodes, new OpCode_ORA(ORA_AbsoluteLongIndexedWithX, new AbsoluteLongIndexedWithXCycles(true)));
    add(opCodes, new OpCode_JSR(JSR_Absolute, new AbsoluteJSRCycles()));
    add(opCodes, new OpCode_AND(AND_DirectPageIndexedIndirectWithX, new DirectIndexedIndirectWithXCycles(true)));
    add(opCodes, new OpCode_JSR(JSL_AbsoluteLong, new AbsoluteLongJSLCycles()));
    add(opCodes, new OpCode_AND(AND_StackRelative, new StackRelativeCycles(true)));
    add(opCodes, new OpCode_BIT(BIT_DirectPage, new DirectCycles(true)));
    add(opCodes, new OpCode_AND(AND_DirectPage, new DirectCycles(true)));
    add(opCodes, new OpCode_ROL_Memory(ROL_DirectPage, new DirectRMWCycles()));
    add(opCodes, new OpCode_AND(AND_DirectPageIndirectLong, new DirectIndirectLongCycles(true)));
    add(opCodes, new OpCode_PLP(PLP_StackImplied, new StackPLPCycles()));
    add(opCodes, new OpCode_AND(AND_Immediate, new ImmediateCycles()));
    add(opCodes, new OpCode_ROL_Memory(ROL_Accumulator, new AccumulatorCycles()));
    add(opCodes, new OpCode_PLD(PLD_StackImplied, new StackPLDCycles()));
    add(opCodes, new OpCode_BIT(BIT_Absolute, new AbsoluteCycles(true)));
    add(opCodes, new OpCode_AND(AND_Absolute, new AbsoluteCycles(true)));
    add(opCodes, new OpCode_ROL_Memory(ROL_Absolute, new AbsoluteRMWCycles()));
    add(opCodes, new OpCode_AND(AND_AbsoluteLong, new AbsoluteLongCycles(true)));
    add(opCodes, new OpCode_BMI(BMI_ProgramCounterRelative, new RelativeCycles()));
    add(opCodes, new OpCode_AND(AND_DirectPageIndirectIndexedWithY, new DirectIndirectIndexedWithYCycles(true)));
    add(opCodes, new OpCode_AND(AND_DirectPageIndirect, new DirectIndirectCycles(true)));
    add(opCodes, new OpCode_AND(AND_StackRelativeIndirectIndexedWithY, new StackRelativeIndirectIndexedWithYCycles(true)));
    add(opCodes, new OpCode_BIT(BIT_DirectPageIndexedWithX, new DirectIndexedWithXCycles(true)));
    add(opCodes, new OpCode_AND(AND_DirectPageIndexedWithX, new DirectIndexedWithXCycles(true)));
    add(opCodes, new OpCode_ROL_Memory(ROL_DirectPageIndexedWithX, new DirectIndexedWithXRMWCycles()));
    add(opCodes, new OpCode_AND(AND_DirectPageIndirectLongIndexedWithY, new DirectIndirectLongIndexedWithYCycles(true)));
    add(opCodes, new OpCode_SEC(SEC_Implied, new ImpliedCycles()));
    add(opCodes, new OpCode_AND(AND_AbsoluteIndexedWithY, new AbsoluteIndexedWithYCycles(true)));
    add(opCodes, new OpCode_DEC_Memory(DEC_Accumulator, new AccumulatorCycles()));
    add(opCodes, new OpCode_TSC(TSC_Implied, new ImpliedCycles()));
    add(opCodes, new OpCode_BIT(BIT_AbsoluteIndexedWithX, new AbsoluteIndexedWithXCycles(true)));
    add(opCodes, new OpCode_AND(AND_AbsoluteIndexedWithX, new AbsoluteIndexedWithXCycles(true)));
    add(opCodes, new OpCode_ROL_Memory(ROL_AbsoluteIndexedWithX, new AbsoluteIndexedWithXRMWCycles()));
    add(opCodes, new OpCode_AND(AND_AbsoluteLongIndexedWithX, new AbsoluteLongIndexedWithXCycles(true)));
    add(opCodes, new OpCode_RTI(RTI_StackImplied, new StackImpliedCycles()));
    add(opCodes, new OpCode_EOR(EOR_DirectPageIndexedIndirectWithX, new DirectIndexedIndirectWithXCycles(true)));
    add(opCodes, new OpCode_WDM(WDM_Implied, new ImpliedCycles()));
    add(opCodes, new OpCode_EOR(EOR_StackRelative, new StackRelativeCycles(true)));
    add(opCodes, new OpCode_MVP(MVP_BlockMove, new BlockMoveCycles()));
    add(opCodes, new OpCode_EOR(EOR_DirectPage, new DirectCycles(true)));
    add(opCodes, new OpCode_LSR(LSR_DirectPage, new DirectRMWCycles()));
    add(opCodes, new OpCode_EOR(EOR_DirectPageIndirectLong, new DirectIndirectLongCycles(true)));
    add(opCodes, new OpCode_PHA(PHA_StackImplied, new StackPHACycles()));
    add(opCodes, new OpCode_EOR(EOR_Immediate, new ImmediateCycles()));
    add(opCodes, new OpCode_LSR(LSR_Accumulator, new AccumulatorCycles()));
    add(opCodes, new OpCode_PHK(PHK_StackImplied, new StackPHKCycles()));
    add(opCodes, new OpCode_JMP(JMP_Absolute, new AbsoluteCycles(true)));
    add(opCodes, new OpCode_EOR(EOR_Absolute, new AbsoluteCycles(true)));
    add(opCodes, new OpCode_LSR(LSR_Absolute, new AbsoluteCycles(true)));
    add(opCodes, new OpCode_EOR(EOR_AbsoluteLong, new AbsoluteLongCycles(true)));
    add(opCodes, new OpCode_BVC(BVC_ProgramCounterRelative, new RelativeCycles()));
    add(opCodes, new OpCode_EOR(EOR_DirectPageIndirectIndexedWithY, new DirectIndirectIndexedWithYCycles(true)));
    add(opCodes, new OpCode_EOR(EOR_DirectPageIndirect, new DirectIndirectCycles(true)));
    add(opCodes, new OpCode_EOR(EOR_StackRelativeIndirectIndexedWithY, new StackRelativeIndirectIndexedWithYCycles(true)));
    add(opCodes, new OpCode_MVN(MVN_BlockMove, new BlockMoveCycles()));
    add(opCodes, new OpCode_EOR(EOR_DirectPageIndexedWithX, new DirectIndexedWithXCycles(true)));
    add(opCodes, new OpCode_LSR(LSR_DirectPageIndexedWithX, new DirectIndexedWithXRMWCycles()));
    add(opCodes, new OpCode_EOR(EOR_DirectPageIndirectLongIndexedWithY, new DirectIndirectLongIndexedWithYCycles(true)));
    add(opCodes, new OpCode_CLI(CLI_Implied, new ImpliedCycles()));
    add(opCodes, new OpCode_EOR(EOR_AbsoluteIndexedWithY, new AbsoluteIndexedWithYCycles(true)));
    add(opCodes, new OpCode_PHY(PHY_StackImplied, new StackPHXPHYCycles()));
    add(opCodes, new OpCode_TCD(TCD_Implied, new ImpliedCycles()));
    add(opCodes, new OpCode_JMP(JMP_AbsoluteLong, new AbsoluteLongCycles(true)));
    add(opCodes, new OpCode_EOR(EOR_AbsoluteIndexedWithX, new AbsoluteIndexedWithXCycles(true)));
    add(opCodes, new OpCode_LSR(LSR_AbsoluteIndexedWithX, new AbsoluteIndexedWithXRMWCycles()));
    add(opCodes, new OpCode_EOR(EOR_AbsoluteLongIndexedWithX, new AbsoluteLongIndexedWithXCycles(true)));
    add(opCodes, new OpCode_RTS(RTS_StackImplied, new StackImpliedCycles()));
    add(opCodes, new OpCode_ADC(ADC_DirectPageIndexedIndirectWithX, new DirectIndexedIndirectWithXCycles(true)));
    add(opCodes, new OpCode_PER(PER_StackProgramCounterRelativeLong, new StackPERCycles()));
    add(opCodes, new OpCode_ADC(ADC_StackRelative, new StackRelativeCycles(true)));
    add(opCodes, new OpCode_STZ(STZ_DirectPage, new DirectCycles(true)));
    add(opCodes, new OpCode_ADC(ADC_DirectPage, new DirectCycles(true)));
    add(opCodes, new OpCode_ROR(ROR_DirectPage, new DirectRMWCycles()));
    add(opCodes, new OpCode_ADC(ADC_DirectPageIndirectLong, new DirectIndirectLongCycles(true)));
    add(opCodes, new OpCode_PLA(PLA_StackImplied, new StackPLACycles()));
    add(opCodes, new OpCode_ADC(ADC_Immediate, new ImmediateCycles()));
    add(opCodes, new OpCode_ROR(ROR_Accumulator, new AccumulatorCycles()));
    add(opCodes, new OpCode_RTL(RTL_StackImplied, new StackImpliedCycles()));
    add(opCodes, new OpCode_JMP(JMP_AbsoluteIndirect, new AbsoluteIndirectJMPCycles()));
    add(opCodes, new OpCode_ADC(ADC_Absolute, new AbsoluteCycles(true)));
    add(opCodes, new OpCode_ROR(ROR_Absolute, new AbsoluteRMWCycles()));
    add(opCodes, new OpCode_ADC(ADC_AbsoluteLong, new AbsoluteLongCycles(true)));
    add(opCodes, new OpCode_BVS(BVS_ProgramCounterRelative, new RelativeCycles()));
    add(opCodes, new OpCode_ADC(ADC_DirectPageIndirectIndexedWithY, new DirectIndirectIndexedWithYCycles(true)));
    add(opCodes, new OpCode_ADC(ADC_DirectPageIndirect, new DirectIndirectCycles(true)));
    add(opCodes, new OpCode_ADC(ADC_StackRelativeIndirectIndexedWithY, new StackRelativeIndirectIndexedWithYCycles(true)));
    add(opCodes, new OpCode_STZ(STZ_DirectPageIndexedWithX, new DirectIndexedWithXCycles(false)));
    add(opCodes, new OpCode_ADC(ADC_DirectPageIndexedWithX, new DirectIndexedWithXCycles(true)));
    add(opCodes, new OpCode_ROR(ROR_DirectPageIndexedWithX, new DirectIndexedWithXRMWCycles()));
    add(opCodes, new OpCode_ADC(ADC_DirectPageIndirectLongIndexedWithY, new DirectIndirectLongIndexedWithYCycles(true)));
    add(opCodes, new OpCode_SEI(SEI_Implied, new ImpliedCycles()));
    add(opCodes, new OpCode_ADC(ADC_AbsoluteIndexedWithY, new AbsoluteIndexedWithYCycles(true)));
    add(opCodes, new OpCode_PLY(PLY_StackImplied, new StackPLXPLYCycles()));
    add(opCodes, new OpCode_TDC(TDC_Implied, new ImpliedCycles()));
    add(opCodes, new OpCode_JMP(JMP_AbsoluteIndexedIndirectWithX, new AbsoluteIndexedIndirectWithXJMPCycles()));
    add(opCodes, new OpCode_ADC(ADC_AbsoluteIndexedWithX, new AbsoluteIndexedWithXCycles(true)));
    add(opCodes, new OpCode_ROR(ROR_AbsoluteIndexedWithX, new AbsoluteIndexedWithXRMWCycles()));
    add(opCodes, new OpCode_ADC(ADC_AbsoluteLongIndexedWithX, new AbsoluteLongIndexedWithXCycles(true)));
    add(opCodes, new OpCode_BRA(BRA_ProgramCounterRelative, new RelativeCycles()));
    add(opCodes, new OpCode_STA(STA_DirectPageIndexedIndirectWithX, new DirectIndexedIndirectWithXCycles(false)));
    add(opCodes, new OpCode_BRL(BRL_ProgramCounterRelativeLong, new RelativeLongCycles()));
    add(opCodes, new OpCode_STA(STA_StackRelative, new StackRelativeCycles(false)));
    add(opCodes, new OpCode_STY(STY_DirectPage, new DirectCycles(false)));
    add(opCodes, new OpCode_STA(STA_DirectPage, new DirectCycles(false)));
    add(opCodes, new OpCode_STX(STX_DirectPage, new DirectCycles(false)));
    add(opCodes, new OpCode_STA(STA_DirectPageIndirectLong, new DirectIndirectLongCycles(false)));
    add(opCodes, new OpCode_DEY(DEY_Implied, new ImpliedCycles()));
    add(opCodes, new OpCode_BIT(BIT_Immediate, new ImmediateCycles()));
    add(opCodes, new OpCode_TXA(TXA_Implied, new ImpliedCycles()));
    add(opCodes, new OpCode_PHB(PHB_StackImplied, new StackPHBCycles()));
    add(opCodes, new OpCode_STY(STY_Absolute, new AbsoluteCycles(false)));
    add(opCodes, new OpCode_STA(STA_Absolute, new AbsoluteCycles(false)));
    add(opCodes, new OpCode_STX(STX_Absolute, new AbsoluteCycles(false)));
    add(opCodes, new OpCode_STA(STA_AbsoluteLong, new AbsoluteLongCycles(false)));
    add(opCodes, new OpCode_BCC(BCC_ProgramCounterRelative, new RelativeCycles()));
    add(opCodes, new OpCode_STA(STA_DirectPageIndirectIndexedWithY, new DirectIndirectIndexedWithYCycles(false)));
    add(opCodes, new OpCode_STA(STA_DirectPageIndirect, new DirectIndirectCycles(false)));
    add(opCodes, new OpCode_STA(STA_StackRelativeIndirectIndexedWithY, new StackRelativeIndirectIndexedWithYCycles(false)));
    add(opCodes, new OpCode_STY(STY_DirectPageIndexedWithX, new DirectIndexedWithXCycles(false)));
    add(opCodes, new OpCode_STA(STA_DirectPageIndexedWithX, new DirectIndexedWithXCycles(false)));
    add(opCodes, new OpCode_STX(STX_DirectPageIndexedWithY, new DirectIndexedWithYCycles(false)));
    add(opCodes, new OpCode_STA(STA_DirectPageIndirectLongIndexedWithY, new DirectIndirectLongIndexedWithYCycles(false)));
    add(opCodes, new OpCode_TYA(TYA_Implied, new ImpliedCycles()));
    add(opCodes, new OpCode_STA(STA_AbsoluteIndexedWithY, new AbsoluteIndexedWithYCycles(false)));
    add(opCodes, new OpCode_TXS(TXS_Implied, new ImpliedCycles()));
    add(opCodes, new OpCode_TXY(TXY_Implied, new ImpliedCycles()));
    add(opCodes, new OpCode_STZ(STZ_Absolute, new AbsoluteCycles(false)));
    add(opCodes, new OpCode_STA(STA_AbsoluteIndexedWithX, new AbsoluteIndexedWithXCycles(false)));
    add(opCodes, new OpCode_STZ(STZ_AbsoluteIndexedWithX, new AbsoluteIndexedWithXCycles(false)));
    add(opCodes, new OpCode_STA(STA_AbsoluteLongIndexedWithX, new AbsoluteLongIndexedWithXCycles(false)));
    add(opCodes, new OpCode_LDY(LDY_Immediate, new ImmediateCycles()));
    add(opCodes, new OpCode_LDA(LDA_DirectPageIndexedIndirectWithX, new DirectIndexedIndirectWithXCycles(true)));
    add(opCodes, new OpCode_LDX(LDX_Immediate, new ImmediateCycles()));
    add(opCodes, new OpCode_LDA(LDA_StackRelative, new StackRelativeCycles(true)));
    add(opCodes, new OpCode_LDY(LDY_DirectPage, new DirectCycles(true)));
    add(opCodes, new OpCode_LDA(LDA_DirectPage, new DirectCycles(true)));
    add(opCodes, new OpCode_LDX(LDX_DirectPage, new DirectCycles(true)));
    add(opCodes, new OpCode_LDA(LDA_DirectPageIndirectLong, new DirectIndirectLongCycles(true)));
    add(opCodes, new OpCode_TAY(TAY_Implied, new ImpliedCycles()));
    add(opCodes, new OpCode_LDA(LDA_Immediate, new ImmediateCycles()));
    add(opCodes, new OpCode_TAX(TAX_Implied, new ImpliedCycles()));
    add(opCodes, new OpCode_PLB(PLB_StackImplied, new StackPLBCycles()));
    add(opCodes, new OpCode_LDY(LDY_Absolute, new AbsoluteCycles(true)));
    add(opCodes, new OpCode_LDA(LDA_Absolute, new AbsoluteCycles(true)));
    add(opCodes, new OpCode_LDX(LDX_Absolute, new AbsoluteCycles(true)));
    add(opCodes, new OpCode_LDA(LDA_AbsoluteLong, new AbsoluteLongCycles(true)));
    add(opCodes, new OpCode_BCS(BCS_ProgramCounterRelative, new RelativeCycles()));
    add(opCodes, new OpCode_LDA(LDA_DirectPageIndirectIndexedWithY, new DirectIndirectIndexedWithYCycles(true)));
    add(opCodes, new OpCode_LDA(LDA_DirectPageIndirect, new DirectIndirectCycles(true)));
    add(opCodes, new OpCode_LDA(LDA_StackRelativeIndirectIndexedWithY, new StackRelativeIndirectIndexedWithYCycles(true)));
    add(opCodes, new OpCode_LDY(LDY_DirectPageIndexedWithX, new DirectIndexedWithXCycles(true)));
    add(opCodes, new OpCode_LDA(LDA_DirectPageIndexedWithX, new DirectIndexedWithXCycles(true)));
    add(opCodes, new OpCode_LDX(LDX_DirectPageIndexedWithY, new DirectIndexedWithYCycles(true)));
    add(opCodes, new OpCode_LDA(LDA_DirectPageIndirectLongIndexedWithY, new DirectIndirectLongIndexedWithYCycles(true)));
    add(opCodes, new OpCode_CLV(CLV_Implied, new ImpliedCycles()));
    add(opCodes, new OpCode_LDA(LDA_AbsoluteIndexedWithY, new AbsoluteIndexedWithYCycles(true)));
    add(opCodes, new OpCode_TSX(TSX_Implied, new ImpliedCycles()));
    add(opCodes, new OpCode_TYX(TYX_Implied, new ImpliedCycles()));
    add(opCodes, new OpCode_LDY(LDY_AbsoluteIndexedWithX, new AbsoluteIndexedWithXCycles(true)));
    add(opCodes, new OpCode_LDA(LDA_AbsoluteIndexedWithX, new AbsoluteIndexedWithXCycles(true)));
    add(opCodes, new OpCode_LDX(LDX_AbsoluteIndexedWithY, new AbsoluteIndexedWithYCycles(true)));
    add(opCodes, new OpCode_LDA(LDA_AbsoluteLongIndexedWithX, new AbsoluteLongIndexedWithXCycles(true)));
    add(opCodes, new OpCode_CPY(CPY_Immediate, new ImmediateCycles()));
    add(opCodes, new OpCode_CMP(CMP_DirectPageIndexedIndirectWithX, new DirectIndexedIndirectWithXCycles(true)));
    add(opCodes, new OpCode_REP(REP_Immediate, new ImmediateCycles()));
    add(opCodes, new OpCode_CMP(CMP_StackRelative, new StackRelativeCycles(true)));
    add(opCodes, new OpCode_CPY(CPY_DirectPage, new DirectCycles(true)));
    add(opCodes, new OpCode_CMP(CMP_DirectPage, new DirectCycles(true)));
    add(opCodes, new OpCode_DEC_Memory(DEC_DirectPage, new DirectRMWCycles()));
    add(opCodes, new OpCode_CMP(CMP_DirectPageIndirectLong, new DirectIndirectLongCycles(true)));
    add(opCodes, new OpCode_INY(INY_Implied, new ImpliedCycles()));
    add(opCodes, new OpCode_CMP(CMP_Immediate, new ImmediateCycles()));
    add(opCodes, new OpCode_DEX(DEX_Implied, new ImpliedCycles()));
    add(opCodes, new OpCode_WAI(WAI_Implied, new ImpliedCycles()));
    add(opCodes, new OpCode_CPY(CPY_Absolute, new AbsoluteCycles(true)));
    add(opCodes, new OpCode_CMP(CMP_Absolute, new AbsoluteCycles(true)));
    add(opCodes, new OpCode_DEC_Memory(DEC_Absolute, new AbsoluteRMWCycles()));
    add(opCodes, new OpCode_CMP(CMP_AbsoluteLong, new AbsoluteLongCycles(true)));
    add(opCodes, new OpCode_BNE(BNE_ProgramCounterRelative, new RelativeCycles()));
    add(opCodes, new OpCode_CMP(CMP_DirectPageIndirectIndexedWithY, new DirectIndirectIndexedWithYCycles(true)));
    add(opCodes, new OpCode_CMP(CMP_DirectPageIndirect, new DirectIndirectCycles(true)));
    add(opCodes, new OpCode_CMP(CMP_StackRelativeIndirectIndexedWithY, new StackRelativeIndirectIndexedWithYCycles(true)));
    add(opCodes, new OpCode_PEI(PEI_StackDirectPageIndirect, new StackPEICycles()));
    add(opCodes, new OpCode_CMP(CMP_DirectPageIndexedWithX, new DirectIndexedWithXCycles(true)));
    add(opCodes, new OpCode_DEC_Memory(DEC_DirectPageIndexedWithX, new DirectIndexedWithXRMWCycles()));
    add(opCodes, new OpCode_CMP(CMP_DirectPageIndirectLongIndexedWithY, new DirectIndirectLongIndexedWithYCycles(true)));
    add(opCodes, new OpCode_CLD(CLD_Implied, new ImpliedCycles()));
    add(opCodes, new OpCode_CMP(CMP_AbsoluteIndexedWithY, new AbsoluteIndexedWithYCycles(true)));
    add(opCodes, new OpCode_PHX(PHX_StackImplied, new StackPHXPHYCycles()));
    add(opCodes, new OpCode_STP(STP_Implied, new ImpliedCycles()));
    add(opCodes, new OpCode_JMP(JML_AbsoluteIndirectLong, new AbsoluteIndirectJMLCycles()));
    add(opCodes, new OpCode_CMP(CMP_AbsoluteIndexedWithX, new AbsoluteIndexedWithXCycles(true)));
    add(opCodes, new OpCode_DEC_Memory(DEC_AbsoluteIndexedWithX, new AbsoluteIndexedWithXRMWCycles()));
    add(opCodes, new OpCode_CMP(CMP_AbsoluteLongIndexedWithX, new AbsoluteLongIndexedWithXCycles(true)));
    add(opCodes, new OpCode_CPX(CPX_Immediate, new ImmediateCycles()));
    add(opCodes, new OpCode_SBC(SBC_DirectPageIndexedIndirectWithX, new DirectIndexedIndirectWithXCycles(true)));
    add(opCodes, new OpCode_SEP(SEP_Immediate, new ImmediateCycles()));
    add(opCodes, new OpCode_SBC(SBC_StackRelative, new StackRelativeCycles(true)));
    add(opCodes, new OpCode_CPX(CPX_DirectPage, new DirectCycles(true)));
    add(opCodes, new OpCode_SBC(SBC_DirectPage, new DirectCycles(true)));
    add(opCodes, new OpCode_INC_Memory(INC_DirectPage, new DirectRMWCycles()));
    add(opCodes, new OpCode_SBC(SBC_DirectPageIndirectLong, new DirectIndirectLongCycles(true)));
    add(opCodes, new OpCode_INX(INX_Implied, new ImpliedCycles()));
    add(opCodes, new OpCode_SBC(SBC_Immediate, new ImmediateCycles()));
    add(opCodes, new OpCode_NOP(NOP_Implied, new ImpliedCycles()));
    add(opCodes, new OpCode_XBA(XBA_Implied, new ImpliedCycles()));
    add(opCodes, new OpCode_CPX(CPX_Absolute, new AbsoluteCycles(true)));
    add(opCodes, new OpCode_SBC(SBC_Absolute, new AbsoluteCycles(true)));
    add(opCodes, new OpCode_INC_Memory(INC_Absolute, new AbsoluteRMWCycles()));
    add(opCodes, new OpCode_SBC(SBC_AbsoluteLong, new AbsoluteLongCycles(true)));
    add(opCodes, new OpCode_BEQ(BEQ_ProgramCounterRelative, new RelativeCycles()));
    add(opCodes, new OpCode_SBC(SBC_DirectPageIndirectIndexedWithY, new DirectIndirectIndexedWithYCycles(true)));
    add(opCodes, new OpCode_SBC(SBC_DirectPageIndirect, new DirectIndirectCycles(true)));
    add(opCodes, new OpCode_SBC(SBC_StackRelativeIndirectIndexedWithY, new StackRelativeIndirectIndexedWithYCycles(true)));
    add(opCodes, new OpCode_PEA(PEA_StackAbsolute, new StackAbsolute));
    add(opCodes, new OpCode_SBC(SBC_DirectPageIndexedWithX, new DirectIndexedWithXCycles(true)));
    add(opCodes, new OpCode_INC_Memory(INC_DirectPageIndexedWithX, new DirectIndexedWithXRMWCycles()));
    add(opCodes, new OpCode_SBC(SBC_DirectPageIndirectLongIndexedWithY, new DirectIndirectLongIndexedWithYCycles(true)));
    add(opCodes, new OpCode_SED(SED_Implied, new ImpliedCycles()));
    add(opCodes, new OpCode_SBC(SBC_AbsoluteIndexedWithY, new AbsoluteIndexedWithYCycles(true)));
    add(opCodes, new OpCode_PLX(PLX_StackImplied, new StackPLXPLYCycles()));
    add(opCodes, new OpCode_XCE(XCE_Implied, new ImpliedCycles()));
    add(opCodes, new OpCode_JSR(JSR_AbsoluteIndexedIndirectWithX, new AbsoluteIndexedIndirectWithXJSRCycles()));
    add(opCodes, new OpCode_SBC(SBC_AbsoluteIndexedWithX, new AbsoluteIndexedWithXCycles(true)));
    add(opCodes, new OpCode_INC_Memory(INC_AbsoluteIndexedWithX, new AbsoluteIndexedWithXRMWCycles()));
    add(opCodes, new OpCode_SBC(SBC_AbsoluteLongIndexedWithX, new AbsoluteLongIndexedWithXCycles(true)));

    for (int i = 0; i <= 255; i++)
    {
      OpCode opCode = opCodes.get(i);
      if (opCode.getCode() != i)
      {
        throw new EmulatorException("OpCode [" + opCode.getName() + "] has code [" + opCode.getCode() + "] but is at index [" + i + "].");
      }
    }

    return opCodes.toArray(new OpCode[0]);
  }

  public static void add(List<OpCode> opCodes, OpCode opCode)
  {
    opCodes.add(opCode);
  }
}

