package name.bizna.emu65816;

import name.bizna.emu65816.addressingmode.*;
import name.bizna.emu65816.interrupt.BRKVector;
import name.bizna.emu65816.interrupt.COPVector;
import name.bizna.emu65816.opcode.*;

import java.util.ArrayList;
import java.util.List;

import static name.bizna.emu65816.OpCodeName.*;
import static name.bizna.emu65816.Width.A;
import static name.bizna.emu65816.Width.XY;

public class OpCodeTable
{
  @SuppressWarnings("DuplicatedCode")
  public static OpCode[] createTable()
  {
    List<OpCode> opCodes = new ArrayList<>();
    add(opCodes, new OpCode_BRK(BRK_Interrupt, new StackSoftwareInterruptCycles(new BRKVector(), Cpu65816::BRK)));
    add(opCodes, new OpCode_ORA(ORA_DirectPageIndexedIndirectWithX, new DirectIndexedIndirectWithXCycles(Cpu65816::ORA)));
    add(opCodes, new OpCode_COP(COP_Interrupt, new StackSoftwareInterruptCycles(new COPVector(), Cpu65816::COP)));
    add(opCodes, new OpCode_ORA(ORA_StackRelative, new StackRelativeCycles(Cpu65816::ORA)));
    add(opCodes, new OpCode_TSB(TSB_DirectPage, new DirectRMWCycles(Cpu65816::TSB)));
    add(opCodes, new OpCode_ORA(ORA_DirectPage, new DirectCycles(Cpu65816::ORA, A)));
    add(opCodes, new OpCode_ASL(ASL_DirectPage, new DirectRMWCycles(Cpu65816::ASL)));
    add(opCodes, new OpCode_ORA(ORA_DirectPageIndirectLong, new DirectIndirectLongCycles(Cpu65816::ORA)));
    add(opCodes, new OpCode_PHP(PHP_StackImplied, new StackImpliedPHPCycles(Cpu65816::PHP)));
    add(opCodes, new OpCode_ORA(ORA_Immediate, new ImmediateCycles(Cpu65816::ORA, A)));
    add(opCodes, new OpCode_ASL_A(ASL_Accumulator, new AccumulatorCycles(Cpu65816::ASL_A)));
    add(opCodes, new OpCode_PHD(PHD_StackImplied, new StackImpliedPHDCycles(Cpu65816::PHD)));
    add(opCodes, new OpCode_TSB(TSB_Absolute, new AbsoluteRMWCycles(Cpu65816::TSB)));
    add(opCodes, new OpCode_ORA(ORA_Absolute, new AbsoluteCycles(Cpu65816::ORA, A)));
    add(opCodes, new OpCode_ASL(ASL_Absolute, new AbsoluteRMWCycles(Cpu65816::ASL)));
    add(opCodes, new OpCode_ORA(ORA_AbsoluteLong, new AbsoluteLongCycles(Cpu65816::ORA)));
    add(opCodes, new OpCode_BPL(BPL_ProgramCounterRelative, new RelativeShortCycles(Cpu65816::BPL)));
    add(opCodes, new OpCode_ORA(ORA_DirectPageIndirectIndexedWithY, new DirectIndirectIndexedWithYCycles(Cpu65816::ORA)));
    add(opCodes, new OpCode_ORA(ORA_DirectPageIndirect, new DirectIndirectCycles(Cpu65816::ORA)));
    add(opCodes, new OpCode_ORA(ORA_StackRelativeIndirectIndexedWithY, new StackRelativeIndirectIndexedWithYCycles(Cpu65816::ORA)));
    add(opCodes, new OpCode_TRB(TRB_DirectPage, new DirectRMWCycles(Cpu65816::TRB)));
    add(opCodes, new OpCode_ORA(ORA_DirectPageIndexedWithX, new DirectIndexedWithXCycles(Cpu65816::ORA, A)));
    add(opCodes, new OpCode_ASL(ASL_DirectPageIndexedWithX, new DirectIndexedWithXRMWCycles(Cpu65816::ASL)));
    add(opCodes, new OpCode_ORA(ORA_DirectPageIndirectLongIndexedWithY, new DirectIndirectLongIndexedWithYCycles(Cpu65816::ORA)));
    add(opCodes, new OpCode_CLC(CLC_Implied, new ImpliedCycles(Cpu65816::CLC)));
    add(opCodes, new OpCode_ORA(ORA_AbsoluteIndexedWithY, new AbsoluteIndexedWithYCycles(Cpu65816::ORA, A)));
    add(opCodes, new OpCode_INC_A(INC_Accumulator, new AccumulatorCycles(Cpu65816::INC_A)));
    add(opCodes, new OpCode_TCS(TCS_Implied, new ImpliedCycles(Cpu65816::TCS)));
    add(opCodes, new OpCode_TRB(TRB_Absolute, new AbsoluteRMWCycles(Cpu65816::TRB)));
    add(opCodes, new OpCode_ORA(ORA_AbsoluteIndexedWithX, new AbsoluteIndexedWithXCycles(Cpu65816::ORA, A)));
    add(opCodes, new OpCode_ASL(ASL_AbsoluteIndexedWithX, new AbsoluteIndexedWithXRMWCycles(Cpu65816::ASL)));
    add(opCodes, new OpCode_ORA(ORA_AbsoluteLongIndexedWithX, new AbsoluteLongIndexedWithXCycles(Cpu65816::ORA)));
    add(opCodes, new OpCode_JSR(JSR_Absolute, new AbsoluteJSRCycles()));
    add(opCodes, new OpCode_AND(AND_DirectPageIndexedIndirectWithX, new DirectIndexedIndirectWithXCycles(Cpu65816::AND)));
    add(opCodes, new OpCode_JSL(JSL_AbsoluteLong, new AbsoluteLongJSLCycles()));
    add(opCodes, new OpCode_AND(AND_StackRelative, new StackRelativeCycles(Cpu65816::AND)));
    add(opCodes, new OpCode_BIT(BIT_DirectPage, new DirectCycles(Cpu65816::BIT, A)));
    add(opCodes, new OpCode_AND(AND_DirectPage, new DirectCycles(Cpu65816::AND, A)));
    add(opCodes, new OpCode_ROL(ROL_DirectPage, new DirectRMWCycles(Cpu65816::ROL)));
    add(opCodes, new OpCode_AND(AND_DirectPageIndirectLong, new DirectIndirectLongCycles(Cpu65816::AND)));
    add(opCodes, new OpCode_PLP(PLP_StackImplied, new StackPLPCycles()));
    add(opCodes, new OpCode_AND(AND_Immediate, new ImmediateCycles(Cpu65816::AND, A)));
    add(opCodes, new OpCode_ROL_A(ROL_Accumulator, new AccumulatorCycles(Cpu65816::ROL_A)));
    add(opCodes, new OpCode_PLD(PLD_StackImplied, new StackPLDCycles(Cpu65816::PLD)));
    add(opCodes, new OpCode_BIT(BIT_Absolute, new AbsoluteCycles(Cpu65816::BIT, A)));
    add(opCodes, new OpCode_AND(AND_Absolute, new AbsoluteCycles(Cpu65816::AND, A)));
    add(opCodes, new OpCode_ROL(ROL_Absolute, new AbsoluteRMWCycles(Cpu65816::ROL)));
    add(opCodes, new OpCode_AND(AND_AbsoluteLong, new AbsoluteLongCycles(Cpu65816::AND)));
    add(opCodes, new OpCode_BMI(BMI_ProgramCounterRelative, new RelativeShortCycles(Cpu65816::BMI)));
    add(opCodes, new OpCode_AND(AND_DirectPageIndirectIndexedWithY, new DirectIndirectIndexedWithYCycles(Cpu65816::AND)));
    add(opCodes, new OpCode_AND(AND_DirectPageIndirect, new DirectIndirectCycles(Cpu65816::AND)));
    add(opCodes, new OpCode_AND(AND_StackRelativeIndirectIndexedWithY, new StackRelativeIndirectIndexedWithYCycles(Cpu65816::AND)));
    add(opCodes, new OpCode_BIT(BIT_DirectPageIndexedWithX, new DirectIndexedWithXCycles(Cpu65816::BIT, A)));
    add(opCodes, new OpCode_AND(AND_DirectPageIndexedWithX, new DirectIndexedWithXCycles(Cpu65816::AND, A)));
    add(opCodes, new OpCode_ROL(ROL_DirectPageIndexedWithX, new DirectIndexedWithXRMWCycles(Cpu65816::ROL)));
    add(opCodes, new OpCode_AND(AND_DirectPageIndirectLongIndexedWithY, new DirectIndirectLongIndexedWithYCycles(Cpu65816::AND)));
    add(opCodes, new OpCode_SEC(SEC_Implied, new ImpliedCycles(Cpu65816::SEC)));
    add(opCodes, new OpCode_AND(AND_AbsoluteIndexedWithY, new AbsoluteIndexedWithYCycles(Cpu65816::AND, A)));
    add(opCodes, new OpCode_DEC_A(DEC_Accumulator, new AccumulatorCycles(Cpu65816::DEC_A)));
    add(opCodes, new OpCode_TSC(TSC_Implied, new ImpliedCycles(Cpu65816::TSC)));
    add(opCodes, new OpCode_BIT(BIT_AbsoluteIndexedWithX, new AbsoluteIndexedWithXCycles(Cpu65816::BIT, A)));
    add(opCodes, new OpCode_AND(AND_AbsoluteIndexedWithX, new AbsoluteIndexedWithXCycles(Cpu65816::AND, A)));
    add(opCodes, new OpCode_ROL(ROL_AbsoluteIndexedWithX, new AbsoluteIndexedWithXRMWCycles(Cpu65816::ROL)));
    add(opCodes, new OpCode_AND(AND_AbsoluteLongIndexedWithX, new AbsoluteLongIndexedWithXCycles(Cpu65816::AND)));
    add(opCodes, new OpCode_RTI(RTI_StackImplied, new StackRTICycles(Cpu65816::RTI)));
    add(opCodes, new OpCode_EOR(EOR_DirectPageIndexedIndirectWithX, new DirectIndexedIndirectWithXCycles(Cpu65816::EOR)));
    add(opCodes, new OpCode_WDM(WDM_Implied, new ImpliedCycles(Cpu65816::WDM)));
    add(opCodes, new OpCode_EOR(EOR_StackRelative, new StackRelativeCycles(Cpu65816::EOR)));
    add(opCodes, new OpCode_MVP(MVP_BlockMove, new BlockMoveCycles(Cpu65816::MVP)));
    add(opCodes, new OpCode_EOR(EOR_DirectPage, new DirectCycles(Cpu65816::EOR, A)));
    add(opCodes, new OpCode_LSR(LSR_DirectPage, new DirectRMWCycles(Cpu65816::LSR)));
    add(opCodes, new OpCode_EOR(EOR_DirectPageIndirectLong, new DirectIndirectLongCycles(Cpu65816::EOR)));
    add(opCodes, new OpCode_PHA(PHA_StackImplied, new StackPushCycles(Cpu65816::PHA, A)));
    add(opCodes, new OpCode_EOR(EOR_Immediate, new ImmediateCycles(Cpu65816::EOR, A)));
    add(opCodes, new OpCode_LSR_A(LSR_Accumulator, new AccumulatorCycles(Cpu65816::LSR_A)));
    add(opCodes, new OpCode_PHK(PHK_StackImplied, new StackPHKCycles(Cpu65816::PHK)));
    add(opCodes, new OpCode_JMP(JMP_Absolute, new AbsoluteJMPCycles()));
    add(opCodes, new OpCode_EOR(EOR_Absolute, new AbsoluteCycles(Cpu65816::EOR, A)));
    add(opCodes, new OpCode_LSR(LSR_Absolute, new AbsoluteRMWCycles(Cpu65816::LSR)));
    add(opCodes, new OpCode_EOR(EOR_AbsoluteLong, new AbsoluteLongCycles(Cpu65816::EOR)));
    add(opCodes, new OpCode_BVC(BVC_ProgramCounterRelative, new RelativeShortCycles(Cpu65816::BVC)));
    add(opCodes, new OpCode_EOR(EOR_DirectPageIndirectIndexedWithY, new DirectIndirectIndexedWithYCycles(Cpu65816::EOR)));
    add(opCodes, new OpCode_EOR(EOR_DirectPageIndirect, new DirectIndirectCycles(Cpu65816::EOR)));
    add(opCodes, new OpCode_EOR(EOR_StackRelativeIndirectIndexedWithY, new StackRelativeIndirectIndexedWithYCycles(Cpu65816::EOR)));
    add(opCodes, new OpCode_MVN(MVN_BlockMove, new BlockMoveCycles(Cpu65816::MVN)));
    add(opCodes, new OpCode_EOR(EOR_DirectPageIndexedWithX, new DirectIndexedWithXCycles(Cpu65816::EOR, A)));
    add(opCodes, new OpCode_LSR(LSR_DirectPageIndexedWithX, new DirectIndexedWithXRMWCycles(Cpu65816::LSR)));
    add(opCodes, new OpCode_EOR(EOR_DirectPageIndirectLongIndexedWithY, new DirectIndirectLongIndexedWithYCycles(Cpu65816::EOR)));
    add(opCodes, new OpCode_CLI(CLI_Implied, new ImpliedCycles(Cpu65816::CLI)));
    add(opCodes, new OpCode_EOR(EOR_AbsoluteIndexedWithY, new AbsoluteIndexedWithYCycles(Cpu65816::EOR, A)));
    add(opCodes, new OpCode_PHY(PHY_StackImplied, new StackPushCycles(Cpu65816::PHY, XY)));
    add(opCodes, new OpCode_TCD(TCD_Implied, new ImpliedCycles(Cpu65816::TCD)));
    add(opCodes, new OpCode_JMP(JML_AbsoluteLong, new AbsoluteLongJMLCycles()));
    add(opCodes, new OpCode_EOR(EOR_AbsoluteIndexedWithX, new AbsoluteIndexedWithXCycles(Cpu65816::EOR, A)));
    add(opCodes, new OpCode_LSR(LSR_AbsoluteIndexedWithX, new AbsoluteIndexedWithXRMWCycles(Cpu65816::LSR)));
    add(opCodes, new OpCode_EOR(EOR_AbsoluteLongIndexedWithX, new AbsoluteLongIndexedWithXCycles(Cpu65816::EOR)));
    add(opCodes, new OpCode_RTS(RTS_StackImplied, new StackRTSCycles()));
    add(opCodes, new OpCode_ADC(ADC_DirectPageIndexedIndirectWithX, new DirectIndexedIndirectWithXCycles(Cpu65816::ADC)));
    add(opCodes, new OpCode_PER(PER_StackProgramCounterRelativeLong, new StackPERCycles(Cpu65816::PER)));
    add(opCodes, new OpCode_ADC(ADC_StackRelative, new StackRelativeCycles(Cpu65816::ADC)));
    add(opCodes, new OpCode_STZ(STZ_DirectPage, new DirectWriteCycles(Cpu65816::STZ, A)));
    add(opCodes, new OpCode_ADC(ADC_DirectPage, new DirectCycles(Cpu65816::ADC, A)));
    add(opCodes, new OpCode_ROR(ROR_DirectPage, new DirectRMWCycles(Cpu65816::ROR)));
    add(opCodes, new OpCode_ADC(ADC_DirectPageIndirectLong, new DirectIndirectLongCycles(Cpu65816::ADC)));
    add(opCodes, new OpCode_PLA(PLA_Stack, new StackPullCycles(Cpu65816::PLA, A)));
    add(opCodes, new OpCode_ADC(ADC_Immediate, new ImmediateCycles(Cpu65816::ADC, A)));
    add(opCodes, new OpCode_ROR_A(ROR_Accumulator, new AccumulatorCycles(Cpu65816::ROR_A)));
    add(opCodes, new OpCode_RTL(RTL_StackImplied, new StackRTLCycles()));
    add(opCodes, new OpCode_JMP(JMP_AbsoluteIndirect, new AbsoluteIndirectJMPCycles()));
    add(opCodes, new OpCode_ADC(ADC_Absolute, new AbsoluteCycles(Cpu65816::ADC, A)));
    add(opCodes, new OpCode_ROR(ROR_Absolute, new AbsoluteRMWCycles(Cpu65816::ROR)));
    add(opCodes, new OpCode_ADC(ADC_AbsoluteLong, new AbsoluteLongCycles(Cpu65816::ADC)));
    add(opCodes, new OpCode_BVS(BVS_ProgramCounterRelative, new RelativeShortCycles(Cpu65816::BVS)));
    add(opCodes, new OpCode_ADC(ADC_DirectPageIndirectIndexedWithY, new DirectIndirectIndexedWithYCycles(Cpu65816::ADC)));
    add(opCodes, new OpCode_ADC(ADC_DirectPageIndirect, new DirectIndirectCycles(Cpu65816::ADC)));
    add(opCodes, new OpCode_ADC(ADC_StackRelativeIndirectIndexedWithY, new StackRelativeIndirectIndexedWithYCycles(Cpu65816::ADC)));
    add(opCodes, new OpCode_STZ(STZ_DirectPageIndexedWithX, new DirectIndexedWithXWriteCycles(Cpu65816::STZ, A)));
    add(opCodes, new OpCode_ADC(ADC_DirectPageIndexedWithX, new DirectIndexedWithXCycles(Cpu65816::ADC, A)));
    add(opCodes, new OpCode_ROR(ROR_DirectPageIndexedWithX, new DirectIndexedWithXRMWCycles(Cpu65816::ROR)));
    add(opCodes, new OpCode_ADC(ADC_DirectPageIndirectLongIndexedWithY, new DirectIndirectLongIndexedWithYCycles(Cpu65816::ADC)));
    add(opCodes, new OpCode_SEI(SEI_Implied, new ImpliedCycles(Cpu65816::SEI)));
    add(opCodes, new OpCode_ADC(ADC_AbsoluteIndexedWithY, new AbsoluteIndexedWithYCycles(Cpu65816::ADC, A)));
    add(opCodes, new OpCode_PLY(PLY_StackImplied, new StackPullCycles(Cpu65816::PLY, XY)));
    add(opCodes, new OpCode_TDC(TDC_Implied, new ImpliedCycles(Cpu65816::TDC)));
    add(opCodes, new OpCode_JMP(JMP_AbsoluteIndexedIndirectWithX, new AbsoluteIndexedIndirectWithXJMPCycles()));
    add(opCodes, new OpCode_ADC(ADC_AbsoluteIndexedWithX, new AbsoluteIndexedWithXCycles(Cpu65816::ADC, A)));
    add(opCodes, new OpCode_ROR(ROR_AbsoluteIndexedWithX, new AbsoluteIndexedWithXRMWCycles(Cpu65816::ROR)));
    add(opCodes, new OpCode_ADC(ADC_AbsoluteLongIndexedWithX, new AbsoluteLongIndexedWithXCycles(Cpu65816::ADC)));
    add(opCodes, new OpCode_BRA(BRA_ProgramCounterRelative, new RelativeShortCycles(Cpu65816::BRA)));
    add(opCodes, new OpCode_STA(STA_DirectPageIndexedIndirectWithX, new DirectIndexedIndirectWithXWriteCycles(Cpu65816::STA)));
    add(opCodes, new OpCode_BRL(BRL_ProgramCounterRelativeLong, new RelativeLongCycles(Cpu65816::BRA)));
    add(opCodes, new OpCode_STA(STA_StackRelative, new StackRelativeWriteCycles(Cpu65816::STA)));
    add(opCodes, new OpCode_STY(STY_DirectPage, new DirectWriteCycles(Cpu65816::STY, XY)));
    add(opCodes, new OpCode_STA(STA_DirectPage, new DirectWriteCycles(Cpu65816::STA, A)));
    add(opCodes, new OpCode_STX(STX_DirectPage, new DirectWriteCycles(Cpu65816::STX, XY)));
    add(opCodes, new OpCode_STA(STA_DirectPageIndirectLong, new DirectIndirectLongWriteCycles(Cpu65816::STA)));
    add(opCodes, new OpCode_DEY(DEY_Implied, new ImpliedCycles(Cpu65816::DEY)));
    add(opCodes, new OpCode_BIT(BIT_Immediate, new ImmediateCycles(Cpu65816::BIT_I, A)));
    add(opCodes, new OpCode_TXA(TXA_Implied, new ImpliedCycles(Cpu65816::TXA)));
    add(opCodes, new OpCode_PHB(PHB_StackImplied, new StackPHBCycles()));
    add(opCodes, new OpCode_STY(STY_Absolute, new AbsoluteWriteCycles(Cpu65816::STY, XY)));
    add(opCodes, new OpCode_STA(STA_Absolute, new AbsoluteWriteCycles(Cpu65816::STA, A)));
    add(opCodes, new OpCode_STX(STX_Absolute, new AbsoluteWriteCycles(Cpu65816::STX, XY)));
    add(opCodes, new OpCode_STA(STA_AbsoluteLong, new AbsoluteLongWriteCycles(Cpu65816::STA, A)));
    add(opCodes, new OpCode_BCC(BCC_ProgramCounterRelative, new RelativeShortCycles(Cpu65816::BCC)));
    add(opCodes, new OpCode_STA(STA_DirectPageIndirectIndexedWithY, new DirectIndirectIndexedWithYWriteCycles(Cpu65816::STA)));
    add(opCodes, new OpCode_STA(STA_DirectPageIndirect, new DirectIndirectWriteCycles(Cpu65816::STA)));
    add(opCodes, new OpCode_STA(STA_StackRelativeIndirectIndexedWithY, new StackRelativeIndirectIndexedWithYWriteCycles(Cpu65816::STA)));
    add(opCodes, new OpCode_STY(STY_DirectPageIndexedWithX, new DirectIndexedWithXWriteCycles(Cpu65816::STY, XY)));
    add(opCodes, new OpCode_STA(STA_DirectPageIndexedWithX, new DirectIndexedWithXWriteCycles(Cpu65816::STA, A)));
    add(opCodes, new OpCode_STX(STX_DirectPageIndexedWithY, new DirectIndexedWithYWriteCycles(Cpu65816::STX, XY)));
    add(opCodes, new OpCode_STA(STA_DirectPageIndirectLongIndexedWithY, new DirectIndirectLongIndexedWithYWriteCycles(Cpu65816::STA)));
    add(opCodes, new OpCode_TYA(TYA_Implied, new ImpliedCycles(Cpu65816::TYA)));
    add(opCodes, new OpCode_STA(STA_AbsoluteIndexedWithY, new AbsoluteIndexedWithYWriteCycles(Cpu65816::STA)));
    add(opCodes, new OpCode_TXS(TXS_Implied, new ImpliedCycles(Cpu65816::TXS)));
    add(opCodes, new OpCode_TXY(TXY_Implied, new ImpliedCycles(Cpu65816::TXY)));
    add(opCodes, new OpCode_STZ(STZ_Absolute, new AbsoluteWriteCycles(Cpu65816::STZ, A)));
    add(opCodes, new OpCode_STA(STA_AbsoluteIndexedWithX, new AbsoluteIndexedWithXWriteCycles(Cpu65816::STA)));
    add(opCodes, new OpCode_STZ(STZ_AbsoluteIndexedWithX, new AbsoluteIndexedWithXWriteCycles(Cpu65816::STZ)));
    add(opCodes, new OpCode_STA(STA_AbsoluteLongIndexedWithX, new AbsoluteLongIndexedWithXWriteCycles(Cpu65816::STA)));
    add(opCodes, new OpCode_LDY(LDY_Immediate, new ImmediateCycles(Cpu65816::LDY, XY)));
    add(opCodes, new OpCode_LDA(LDA_DirectPageIndexedIndirectWithX, new DirectIndexedIndirectWithXCycles(Cpu65816::LDA)));
    add(opCodes, new OpCode_LDX(LDX_Immediate, new ImmediateCycles(Cpu65816::LDX, XY)));
    add(opCodes, new OpCode_LDA(LDA_StackRelative, new StackRelativeCycles(Cpu65816::LDA)));
    add(opCodes, new OpCode_LDY(LDY_DirectPage, new DirectCycles(Cpu65816::LDY, XY)));
    add(opCodes, new OpCode_LDA(LDA_DirectPage, new DirectCycles(Cpu65816::LDA, A)));
    add(opCodes, new OpCode_LDX(LDX_DirectPage, new DirectCycles(Cpu65816::LDX, XY)));
    add(opCodes, new OpCode_LDA(LDA_DirectPageIndirectLong, new DirectIndirectLongCycles(Cpu65816::LDA)));
    add(opCodes, new OpCode_TAY(TAY_Implied, new ImpliedCycles(Cpu65816::TAY)));
    add(opCodes, new OpCode_LDA(LDA_Immediate, new ImmediateCycles(Cpu65816::LDA, A)));
    add(opCodes, new OpCode_TAX(TAX_Implied, new ImpliedCycles(Cpu65816::TAX)));
    add(opCodes, new OpCode_PLB(PLB_StackImplied, new StackPLBCycles()));
    add(opCodes, new OpCode_LDY(LDY_Absolute, new AbsoluteCycles(Cpu65816::LDY, XY)));
    add(opCodes, new OpCode_LDA(LDA_Absolute, new AbsoluteCycles(Cpu65816::LDA, A)));
    add(opCodes, new OpCode_LDX(LDX_Absolute, new AbsoluteCycles(Cpu65816::LDX, XY)));
    add(opCodes, new OpCode_LDA(LDA_AbsoluteLong, new AbsoluteLongCycles(Cpu65816::LDA)));
    add(opCodes, new OpCode_BCS(BCS_ProgramCounterRelative, new RelativeShortCycles(Cpu65816::BCS)));
    add(opCodes, new OpCode_LDA(LDA_DirectPageIndirectIndexedWithY, new DirectIndirectIndexedWithYCycles(Cpu65816::LDA)));
    add(opCodes, new OpCode_LDA(LDA_DirectPageIndirect, new DirectIndirectCycles(Cpu65816::LDA)));
    add(opCodes, new OpCode_LDA(LDA_StackRelativeIndirectIndexedWithY, new StackRelativeIndirectIndexedWithYCycles(Cpu65816::LDA)));
    add(opCodes, new OpCode_LDY(LDY_DirectPageIndexedWithX, new DirectIndexedWithXCycles(Cpu65816::LDY, XY)));
    add(opCodes, new OpCode_LDA(LDA_DirectPageIndexedWithX, new DirectIndexedWithXCycles(Cpu65816::LDA, A)));
    add(opCodes, new OpCode_LDX(LDX_DirectPageIndexedWithY, new DirectIndexedWithYCycles(Cpu65816::LDX, XY)));
    add(opCodes, new OpCode_LDA(LDA_DirectPageIndirectLongIndexedWithY, new DirectIndirectLongIndexedWithYCycles(Cpu65816::LDA)));
    add(opCodes, new OpCode_CLV(CLV_Implied, new ImpliedCycles(Cpu65816::CLV)));
    add(opCodes, new OpCode_LDA(LDA_AbsoluteIndexedWithY, new AbsoluteIndexedWithYCycles(Cpu65816::LDA, A)));
    add(opCodes, new OpCode_TSX(TSX_Implied, new ImpliedCycles(Cpu65816::TSX)));
    add(opCodes, new OpCode_TYX(TYX_Implied, new ImpliedCycles(Cpu65816::TYX)));
    add(opCodes, new OpCode_LDY(LDY_AbsoluteIndexedWithX, new AbsoluteIndexedWithXCycles(Cpu65816::LDY, XY)));
    add(opCodes, new OpCode_LDA(LDA_AbsoluteIndexedWithX, new AbsoluteIndexedWithXCycles(Cpu65816::LDA, A)));
    add(opCodes, new OpCode_LDX(LDX_AbsoluteIndexedWithY, new AbsoluteIndexedWithYCycles(Cpu65816::LDX, XY)));
    add(opCodes, new OpCode_LDA(LDA_AbsoluteLongIndexedWithX, new AbsoluteLongIndexedWithXCycles(Cpu65816::LDA)));
    add(opCodes, new OpCode_CPY(CPY_Immediate, new ImmediateCycles(Cpu65816::CPY, XY)));
    add(opCodes, new OpCode_CMP(CMP_DirectPageIndexedIndirectWithX, new DirectIndexedIndirectWithXCycles(Cpu65816::CMP)));
    add(opCodes, new OpCode_REP(REP_Immediate, new ImmediateREPSEPCycles(Cpu65816::REP)));
    add(opCodes, new OpCode_CMP(CMP_StackRelative, new StackRelativeCycles(Cpu65816::CMP)));
    add(opCodes, new OpCode_CPY(CPY_DirectPage, new DirectCycles(Cpu65816::CPY, XY)));
    add(opCodes, new OpCode_CMP(CMP_DirectPage, new DirectCycles(Cpu65816::CMP, A)));
    add(opCodes, new OpCode_DEC(DEC_DirectPage, new DirectRMWCycles(Cpu65816::DEC)));
    add(opCodes, new OpCode_CMP(CMP_DirectPageIndirectLong, new DirectIndirectLongCycles(Cpu65816::CMP)));
    add(opCodes, new OpCode_INY(INY_Implied, new ImpliedCycles(Cpu65816::INY)));
    add(opCodes, new OpCode_CMP(CMP_Immediate, new ImmediateCycles(Cpu65816::CMP, A)));
    add(opCodes, new OpCode_DEX(DEX_Implied, new ImpliedCycles(Cpu65816::DEX)));
    add(opCodes, new OpCode_WAI(WAI_Implied, new WaitForInterruptCycles(Cpu65816::WAI)));
    add(opCodes, new OpCode_CPY(CPY_Absolute, new AbsoluteCycles(Cpu65816::CPY, XY)));
    add(opCodes, new OpCode_CMP(CMP_Absolute, new AbsoluteCycles(Cpu65816::CMP, A)));
    add(opCodes, new OpCode_DEC(DEC_Absolute, new AbsoluteRMWCycles(Cpu65816::DEC)));
    add(opCodes, new OpCode_CMP(CMP_AbsoluteLong, new AbsoluteLongCycles(Cpu65816::CMP)));
    add(opCodes, new OpCode_BNE(BNE_ProgramCounterRelative, new RelativeShortCycles(Cpu65816::BNE)));
    add(opCodes, new OpCode_CMP(CMP_DirectPageIndirectIndexedWithY, new DirectIndirectIndexedWithYCycles(Cpu65816::CMP)));
    add(opCodes, new OpCode_CMP(CMP_DirectPageIndirect, new DirectIndirectCycles(Cpu65816::CMP)));
    add(opCodes, new OpCode_CMP(CMP_StackRelativeIndirectIndexedWithY, new StackRelativeIndirectIndexedWithYCycles(Cpu65816::CMP)));
    add(opCodes, new OpCode_PEI(PEI_StackDirectPageIndirect, new StackPEICycles()));
    add(opCodes, new OpCode_CMP(CMP_DirectPageIndexedWithX, new DirectIndexedWithXCycles(Cpu65816::CMP, A)));
    add(opCodes, new OpCode_DEC(DEC_DirectPageIndexedWithX, new DirectIndexedWithXRMWCycles(Cpu65816::DEC)));
    add(opCodes, new OpCode_CMP(CMP_DirectPageIndirectLongIndexedWithY, new DirectIndirectLongIndexedWithYCycles(Cpu65816::CMP)));
    add(opCodes, new OpCode_CLD(CLD_Implied, new ImpliedCycles(Cpu65816::CLD)));
    add(opCodes, new OpCode_CMP(CMP_AbsoluteIndexedWithY, new AbsoluteIndexedWithYCycles(Cpu65816::CMP, A)));
    add(opCodes, new OpCode_PHX(PHX_StackImplied, new StackPushCycles(Cpu65816::PHX, XY)));
    add(opCodes, new OpCode_STP(STP_Implied, new StopTheClockCycles(Cpu65816::STP)));
    add(opCodes, new OpCode_JMP(JML_AbsoluteIndirectLong, new AbsoluteIndirectJMLCycles()));
    add(opCodes, new OpCode_CMP(CMP_AbsoluteIndexedWithX, new AbsoluteIndexedWithXCycles(Cpu65816::CMP, A)));
    add(opCodes, new OpCode_DEC(DEC_AbsoluteIndexedWithX, new AbsoluteIndexedWithXRMWCycles(Cpu65816::DEC)));
    add(opCodes, new OpCode_CMP(CMP_AbsoluteLongIndexedWithX, new AbsoluteLongIndexedWithXCycles(Cpu65816::CMP)));
    add(opCodes, new OpCode_CPX(CPX_Immediate, new ImmediateCycles(Cpu65816::CPX, XY)));
    add(opCodes, new OpCode_SBC(SBC_DirectPageIndexedIndirectWithX, new DirectIndexedIndirectWithXCycles(Cpu65816::SBC)));
    add(opCodes, new OpCode_SEP(SEP_Immediate, new ImmediateREPSEPCycles(Cpu65816::SEP)));
    add(opCodes, new OpCode_SBC(SBC_StackRelative, new StackRelativeCycles(Cpu65816::SBC)));
    add(opCodes, new OpCode_CPX(CPX_DirectPage, new DirectCycles(Cpu65816::CPX, XY)));
    add(opCodes, new OpCode_SBC(SBC_DirectPage, new DirectCycles(Cpu65816::SBC, A)));
    add(opCodes, new OpCode_INC(INC_DirectPage, new DirectRMWCycles(Cpu65816::INC)));
    add(opCodes, new OpCode_SBC(SBC_DirectPageIndirectLong, new DirectIndirectLongCycles(Cpu65816::SBC)));
    add(opCodes, new OpCode_INX(INX_Implied, new ImpliedCycles(Cpu65816::INX)));
    add(opCodes, new OpCode_SBC(SBC_Immediate, new ImmediateCycles(Cpu65816::SBC, A)));
    add(opCodes, new OpCode_NOP(NOP_Implied, new ImpliedCycles(Cpu65816::NOP)));
    add(opCodes, new OpCode_XBA(XBA_Implied, new ImpliedXBACycles(Cpu65816::XBA)));
    add(opCodes, new OpCode_CPX(CPX_Absolute, new AbsoluteCycles(Cpu65816::CPX, XY)));
    add(opCodes, new OpCode_SBC(SBC_Absolute, new AbsoluteCycles(Cpu65816::SBC, A)));
    add(opCodes, new OpCode_INC(INC_Absolute, new AbsoluteRMWCycles(Cpu65816::INC)));
    add(opCodes, new OpCode_SBC(SBC_AbsoluteLong, new AbsoluteLongCycles(Cpu65816::SBC)));
    add(opCodes, new OpCode_BEQ(BEQ_ProgramCounterRelative, new RelativeShortCycles(Cpu65816::BEQ)));
    add(opCodes, new OpCode_SBC(SBC_DirectPageIndirectIndexedWithY, new DirectIndirectIndexedWithYCycles(Cpu65816::SBC)));
    add(opCodes, new OpCode_SBC(SBC_DirectPageIndirect, new DirectIndirectCycles(Cpu65816::SBC)));
    add(opCodes, new OpCode_SBC(SBC_StackRelativeIndirectIndexedWithY, new StackRelativeIndirectIndexedWithYCycles(Cpu65816::SBC)));
    add(opCodes, new OpCode_PEA(PEA_StackImmediate, new StackPEACycles()));
    add(opCodes, new OpCode_SBC(SBC_DirectPageIndexedWithX, new DirectIndexedWithXCycles(Cpu65816::SBC, A)));
    add(opCodes, new OpCode_INC(INC_DirectPageIndexedWithX, new DirectIndexedWithXRMWCycles(Cpu65816::INC)));
    add(opCodes, new OpCode_SBC(SBC_DirectPageIndirectLongIndexedWithY, new DirectIndirectLongIndexedWithYCycles(Cpu65816::SBC)));
    add(opCodes, new OpCode_SED(SED_Implied, new ImpliedCycles(Cpu65816::SED)));
    add(opCodes, new OpCode_SBC(SBC_AbsoluteIndexedWithY, new AbsoluteIndexedWithYCycles(Cpu65816::SBC, A)));
    add(opCodes, new OpCode_PLX(PLX_StackImplied, new StackPullCycles(Cpu65816::PLX, XY)));
    add(opCodes, new OpCode_XCE(XCE_Implied, new ImpliedCycles(Cpu65816::XCE)));
    add(opCodes, new OpCode_JSR(JSR_AbsoluteIndexedIndirectWithX, new AbsoluteIndexedIndirectWithXJSRCycles()));
    add(opCodes, new OpCode_SBC(SBC_AbsoluteIndexedWithX, new AbsoluteIndexedWithXCycles(Cpu65816::SBC, A)));
    add(opCodes, new OpCode_INC(INC_AbsoluteIndexedWithX, new AbsoluteIndexedWithXRMWCycles(Cpu65816::INC)));
    add(opCodes, new OpCode_SBC(SBC_AbsoluteLongIndexedWithX, new AbsoluteLongIndexedWithXCycles(Cpu65816::SBC)));

    for (int i = 0; i <= 255; i++)
    {
      OpCode opCode = opCodes.get(i);
      if (opCode.getCode() != i)
      {
        throw new EmulatorException("OpCode [" + opCode.getName() + "] has code [" + opCode.getCode() + "] but is at index [" + i + "].");
      }
    }

    return opCodes.toArray(new OpCode[0]);
  }

  public static void add(List<OpCode> opCodes, OpCode opCode)
  {
    opCodes.add(opCode);
  }
}

