M48
; DRILL file {KiCad 9.0.4} date 2025-08-27T20:16:34+0200
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-08-27T20:16:34+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1311
%
G90
G05
T1
X-0.23Y0.05
X-0.23Y-2.05
X4.1Y0.475
X4.1Y-1.625
X4.3219Y-1.985
X4.3219Y-2.485
M30
