M48
; DRILL file {KiCad 7.0.5} date Mon Dec 18 16:36:42 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-12-18T16:36:42+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0394
%
G90
G05
T1
X4.5Y-2.1
X4.5Y-2.2
X4.5Y-2.3
X4.7Y-2.1
X4.7Y-2.2
X4.7Y-2.3
X5.2Y-2.1
X5.2Y-2.2
X5.2Y-2.3
T0
M30
